modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/SuperSpaceEye/Some-Peripherals/issues"
[[mods]]
modId="some_peripherals"
version="${version}"
displayName="Some Peripherals" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://modrinth.com/mod/some-peripherals/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #optional
description='''
A mod that adds various peripherals.
'''
authors = "SpaceEye"
credits="Contributors: Illuc, Tetrode, sashafiesta"
[[dependencies.some_peripherals]]
   modId="forge" #mandatory
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="[41,)" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.some_peripherals]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="BOTH"
[[dependencies.some_peripherals]]
   modId="kotlinforforge"
   mandatory=true
   versionRange="[3,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.some_peripherals]]
   modId="architectury"
   mandatory=true
   versionRange="[4.11.93,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.some_peripherals]]
   modId="computercraft"
   mandatory=false
   versionRange="[1.101.0,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.some_peripherals]]
   modId="valkyrienskies"
   mandatory=false
   versionRange="[2,)"
   ordering="NONE"
   side="BOTH"